repositories:
  - name: traefik
    url: https://traefik.github.io/charts
  - name: seaweedfs
    url: https://seaweedfs.github.io/seaweedfs/helm
  - name: aws-mountpoint-s3-csi-driver
    url: https://awslabs.github.io/mountpoint-s3-csi-driver
---
helmDefaults:
  atomic: true
  wait: true
  timeout: 600
  createNamespace: true
---
environments:
  default:
    values:
      - environments/minikube/values.yaml
  minikube:
    values:
      - environments/minikube/values.yaml
---
releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 41.2.0
    disableValidationOnInstall: true
    values:
      - environments/minikube/traefik-values.yaml.gotmpl

  - name: seaweedfs
    namespace: seaweedfs
    needs:
      - traefik/traefik
    chart: seaweedfs/seaweedfs
    version: 4.20.0
    values:
      - environments/minikube/seaweedfs-values.yaml.gotmpl

  - name: aws-mountpoint-s3-csi-driver
    namespace: kube-system
    needs:
      - seaweedfs/seaweedfs
    chart: ./charts/aws-mountpoint-s3-csi-driver-wrapper
    values:
      - environments/minikube/aws-mountpoint-s3-csi-driver-wrapper-values.yaml.gotmpl
