controller:
  replicaCount: 1
  ingressClass: nginx
  ingressClassResource:
    name: nginx
    enabled: true
    default: false
    controllerValue: k8s.io/ingress-nginx
  watchIngressWithoutClass: false
  ingressClassByName: true
  publishService:
    enabled: true
  service:
    type: LoadBalancer
  admissionWebhooks:
    enabled: true
