apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  key_id: {{ .Values.accessKeyId | quote }}
  access_key: {{ .Values.secretAccessKey | quote }}
